trigger:
  branches:
    include:
      - main
      - feature/*

pr:
  branches:
    include:
      - main
      - feature/*

pool:
  name: sumsungprojectagentpool
  demands:
    - Agent.Name -equals DESKTOP-7H76R0M

variables:
  terraformVersion: '1.6.6'
  workingDir: '$(System.DefaultWorkingDirectory)'

stages:
  - stage: TerraformValidation
    displayName: 'Terraform Init Fmt Validate Plan'

    jobs:
      - job: TerraformJob
        displayName: 'Terraform CI'

        steps:
          - checkout: self

          # Install Terraform
          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: $(terraformVersion)

          # Terraform Init
          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: $(workingDir)
              backendServiceArm: 'sumsungprojectservcon'

          # Terraform Format Check
          - task: TerraformTaskV4@4
            displayName: 'Terraform Fmt'
            inputs:
              provider: 'azurerm'
              command: 'custom'
              workingDirectory: $(workingDir)
              customCommand: 'fmt -check -recursive'

          # Terraform Validate
          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: $(workingDir)

          # Terraform Plan
          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: $(workingDir)
              environmentServiceNameAzureRM: 'sumsungprojectservcon'